#!/bin/bash
# CreditPathAI Deployment Script for Render.com

# This script helps you deploy CreditPathAI to make it accessible from anywhere

echo "========================================="
echo "CreditPathAI - Quick Deployment Guide"
echo "========================================="
echo ""
echo "Follow these steps to make your app accessible from anywhere:"
echo ""
echo "STEP 1: Create GitHub Account"
echo "  → Go to: https://github.com/signup"
echo "  → Create a free account"
echo ""
echo "STEP 2: Create New Repository on GitHub"
echo "  → Go to: https://github.com/new"
echo "  → Repository name: CreditPathAI"
echo "  → Make it Public"
echo "  → Click 'Create repository'"
echo ""
echo "STEP 3: Push Your Code (Run these commands):"
echo ""
echo "  cd c:/Users/saikrishna/Downloads/Desktop/infosys_project/CreditPathAI"
echo "  git init"
echo "  git add ."
echo "  git commit -m \"Initial commit - CreditPathAI\""
echo "  git branch -M main"
echo "  git remote add origin https://github.com/YOUR_USERNAME/CreditPathAI.git"
echo "  git push -u origin main"
echo ""
echo "  (Replace YOUR_USERNAME with your GitHub username)"
echo ""
echo "STEP 4: Deploy on Render.com"
echo "  → Go to: https://render.com"
echo "  → Click 'Get Started for Free'"
echo "  → Sign in with GitHub"
echo "  → Click 'New +' → 'Web Service'"
echo "  → Select 'CreditPathAI' repository"
echo "  → Configure:"
echo "     Name: creditpathai"
echo "     Environment: Python 3"
echo "     Build Command: pip install -r requirements.txt"
echo "     Start Command: cd backend/app && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "  → Click 'Create Web Service'"
echo ""
echo "STEP 5: Wait for Deployment (5-10 minutes)"
echo "  → Render will automatically build and deploy"
echo "  → You'll see progress in the logs"
echo ""
echo "STEP 6: Get Your Public URL!"
echo "  → Once deployed, you'll get a URL like:"
echo "     https://creditpathai.onrender.com"
echo ""
echo "========================================="
echo "🎉 DONE! Your app will be accessible from:"
echo "  ✅ Any computer (Windows, Mac, Linux)"
echo "  ✅ Any phone (iPhone, Android)"
echo "  ✅ Any tablet"
echo "  ✅ Anywhere in the world with internet"
echo "========================================="
echo ""
echo "Need help? Check the full guide at:"
echo "  c:/Users/saikrishna/.gemini/antigravity/brain/3a2893b3-5388-4a3d-bf3b-f8795b9d2a13/deployment_guide.md"
